twig:
    file_name_pattern: '*.twig'
    globals:
        dataProvider: '@App\Service\DataProviderService'
        # category: '@app.repository.category'
when@test:
    twig:
        strict_variables: true
