controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# formationadistanceetenligne:
#     path: /ecole/formationadistanceetenligne
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#     defaults:
#         template: 'ecole/formationadistanceetenligne.html.twig'
